package demo.client.shared;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ADDRESS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ADDRESS_ID_SEQ", name = "ADDRESS_ID_GENERATOR")
   private Long id;

   @org.kie.api.definition.type.Label("Street Name")
   private String street;

   @org.kie.api.definition.type.Label("Number")
   private Integer number;

   @org.kie.api.definition.type.Label("Door")
   private String door;

   @org.kie.api.definition.type.Label("CP")
   private String cp;

   @org.kie.api.definition.type.Label("City")
   private String city;

   public Address()
   {
   }

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   public String getStreet()
   {
      return this.street;
   }

   public void setStreet(String street)
   {
      this.street = street;
   }

   public Integer getNumber()
   {
      return this.number;
   }

   public void setNumber(Integer number)
   {
      this.number = number;
   }

   public String getDoor()
   {
      return door;
   }

   public void setDoor(String door)
   {
      this.door = door;
   }

   public String getCp()
   {
      return this.cp;
   }

   public void setCp(String cp)
   {
      this.cp = cp;
   }

   public String getCity()
   {
      return this.city;
   }

   public void setCity(String city)
   {
      this.city = city;
   }

   public Address(java.lang.Long id, java.lang.String street,
         java.lang.Integer number, java.lang.String door, java.lang.String cp,
         java.lang.String city)
   {
      this.id = id;
      this.street = street;
      this.number = number;
      this.door = door;
      this.cp = cp;
      this.city = city;
   }

}